export const FINALISE_GAME_REQUEST = 'FINALISE_GAME_REQUEST';
export const FINALISE_GAME_SUCCESS = 'FINALISE_GAME_SUCCESS';
export const FINALISE_GAME_FAILED = 'FINALISE_GAME_FAILED';

export const RESET_GAME_REQUEST = 'RESET_GAME_REQUEST';
export const RESET_GAME_SUCCESS = 'RESET_GAME_SUCCESS';
export const RESET_GAME_FAILED = 'RESET_GAME_FAILED';

export const FETCH_PLAYERS_REQUEST = 'FETCH_PLAYERS_REQUEST';
export const PLAYERS_FAILED = 'PLAYERS_FAILED';
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_ACT = 'UPDATE_PLAYER_ACT';
export const UPDATE_PLAYER_ST1 = 'UPDATE_PLAYER_ST1';
export const UPDATE_PLAYER_ST2 = 'UPDATE_PLAYER_ST2';
export const UPDATE_PLAYER_ADDR = 'UPDATE_PLAYER_ADDR';
export const UPDATE_PLAYER_PL2 = 'UPDATE_PLAYER_PL2';

export const FETCH_STATUS_REQUEST = 'FETCH_STATUS_REQUEST';
export const STATUS_FAILED = 'STATUS_FAILED';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_COUNT = 'UPDATE_STATUS_COUNT';
export const UPDATE_STATUS_FINALISED = 'UPDATE_STATUS_FINALISED';
export const UPDATE_STATUS_ACT = 'UPDATE_STATUS_ACT';
export const UPDATE_STATUS_TIMER = 'UPDATE_STATUS_TIMER';

export const SUBMIT_COMMIT_REQUEST = 'SUBMIT_COMMIT_REQUEST';
export const SUBMIT_COMMIT_SUCCESS = 'SUBMIT_COMMIT_SUCCESS';
export const SUBMIT_COMMIT_FAILED = 'SUBMIT_COMMIT_FAILED';

export const REVEAL_COMMIT_REQUEST = 'REVEAL_COMMIT_REQUEST';
export const REVEAL_COMMIT_SUCCESS = 'REVEAL_COMMIT_SUCCESS';
export const REVEAL_COMMIT_FAILED = 'REVEAL_COMMIT_FAILED';